Controllers/CartController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Handmade_Dotnet.Models;

namespace Handmade_Dotnet.Controllers;

public class CartController : Controller
{
    public ProductService productService=new ProductService();
    public UserCartService userCartService=new UserCartService();
    public IActionResult Index()
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        List<ProductModel> cartProducts = userCartService.GetByUsername(username); //---------------------------
        ViewBag.cartProducts = cartProducts;
        List<UserCartModel> cart=userCartService.GetAll(username);
        ViewBag.cart = cart;
        List<ProductModel> products = productService.GetAll();
        ViewBag.products = products;
        ViewBag.username=username;
        return View();
    }

    public IActionResult AddProduct(String id)
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        // var product=userCartService.GetByUsername(username);
        var p=userCartService.GetById(id,username);
        if (p != null) {p.Quantity+=1; userCartService.Update(p);}
        else{
        UserCartModel userCartModel= new UserCartModel(username,id,1);
        userCartService.Add(userCartModel);
        }
        return Redirect(Request.Headers.Referer.ToString());
    }

    public IActionResult DeleteProduct(String id)
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        userCartService.Delete(id,username);
        return Redirect(Request.Headers.Referer.ToString());
    }

    public IActionResult UpdateQuantity(int id,string productId)
    {
        Console.WriteLine($"Received quantity: {id}, productId: {productId}");
        userCartService.SetQuantity(id,productId);
        return Redirect(Request.Headers.Referer.ToString());
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/HeartController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Handmade_Dotnet.Models;

namespace Handmade_Dotnet.Controllers;

public class HeartController : Controller
{
    public ProductService productService = new ProductService();
    public TutorialService tutorialService= new TutorialService();
    public FavoriteProductsService favoriteProductsService= new FavoriteProductsService();
    public FavoriteTutorialsService favoriteTutorialsService= new FavoriteTutorialsService();
    public IActionResult Index()
    {
        var username = HttpContext.Session.GetString("ten_user");
         if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        List<ProductModel> favoriteProducts=favoriteProductsService.GetByUsername(username);//-----------------
        ViewBag.favoriteProducts = favoriteProducts;
        List<ProductModel> products = productService.GetAll();
        ViewBag.products = products;
        List<TutorialModel> favoriteTutorials=favoriteTutorialsService.GetByUsername(username);
        ViewBag.favoriteTutorials = favoriteTutorials;
        List<TutorialModel> tutorials = tutorialService.GetAll();
        ViewBag.tutorials = tutorials;
        ViewBag.username=username;
        return View();
    }

    public IActionResult AddProduct(String id)
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
        {
            return RedirectToAction("Index", "Login");
        }
        FavoriteProductModel favoriteProductModel= new FavoriteProductModel(username,id);
        favoriteProductsService.Add(favoriteProductModel);
        return Redirect(Request.Headers.Referer.ToString());
    }

     public IActionResult AddTutorial(String id)
    {
        var username = HttpContext.Session.GetString("ten_user");
         if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        FavoriteTutorialModel favoriteTutorial=new FavoriteTutorialModel(username,id);
        favoriteTutorialsService.Add(favoriteTutorial);
        return Redirect(Request.Headers.Referer.ToString());
    }

    public IActionResult DeleteProduct(String id)
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        favoriteProductsService.Delete(id,username);
        return Redirect(Request.Headers.Referer.ToString());
    }

    public ActionResult DeleteTutorial(String id)
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        favoriteTutorialsService.Delete(id,username);
        return Redirect(Request.Headers.Referer.ToString());
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LogoutController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Handmade_Dotnet.Models;

namespace Handmade_Dotnet.Controllers;

public class LogoutController : Controller
{
    public IActionResult Index()
    {
        HttpContext.Session.Clear();
        return RedirectToAction("Index", "Login");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - Handmade_Dotnet</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
  <link rel="stylesheet" href="~/css/Style.css" asp-append-version="true" />
</head>

<body>
  <header>
    <input type="checkbox" name="" id="toggler" />
    <label for="toggler" class="fas fa-bars"></label>

    <a class="logo" asp-area="" asp-controller="Home" asp-action="Index">Handmade<span>.</span></a>

    <nav class="navbar">
      <a href="@Href("/Home#home")">Trang Chủ</a>
      <a href="@Href("/Home#about")">Giới Thiệu</a>
      <a href="@Href("/Home#products")">Sản Phẩm</a>
      <a href="@Href("/Home#tutorial")">Hướng Dẫn</a>
      <a href="@Href("/Home#review")">Đánh Giá</a>
      <a href="@Href("/Home#contact")">Liên Hệ</a>
    </nav>

    <div class="icons">
      <i class="fas fa-search" id="search-icon"></i>
      <a class="fas fa-heart" asp-area="" asp-controller="Heart" asp-action="Index"></a>
      <a class="fas fa-shopping-cart" asp-area="" asp-controller="Cart" asp-action="Index"></a>
      @{
        var username = ViewBag.username;
        if (string.IsNullOrEmpty(username))
        {
          <a class="fas fa-user" asp-area="" asp-controller="Logout" asp-action="Index"></a>
        }
        else
        {
          <a class="fa-solid fa-arrow-right-from-bracket" asp-area="" asp-controller="Login" asp-action="Index"></a>
        }
      }
      @* <a class="fas fa-user" asp-area="" asp-controller="Login" asp-action="Index"></a> *@
    </div>

    <form action="" class="search-form">
      <input type="search" name="" placeholder="Tìm kiếm..." id="search-box" />
      <label for="search-box" class="fas fa-search"></label>
    </form>
  </header>
  @RenderBody()
  <section class="footer">
    <div class="box-container">
      <div class="box">
        <h3>Mục Lục</h3>
        <a href="./HomeView.html#">Trang Chủ</a>
        <a href="./HomeView.html#about">Giới Thiệu</a>
        <a href="./HomeView.html#products">Sản Phẩm</a>
        <a href="./HomeView.html#tutorial">Hướng Dẫn</a>
        <a href="./HomeView.html#review">Đánh Giá</a>
        <a href="./HomeView.html#contact">Liên Hệ</a>
      </div>

      <div class="box">
        <h3>Tài Khoản</h3>
        <a href="./HeartView.html">Mục Yêu Thích</a>
        <a href="./CartView.html">Đơn Hàng Của Tôi</a>
        <a href="./LoginView.html">Tài Khoản Của Tôi</a>
      </div>

      <div class="box">
        <h3>Hỗ Trợ</h3>
        <a href="#">Mua Hàng</a>
        <a href="#">Bán Hàng</a>
        <a href="#">Thanh Toán</a>
        <a href="#">Trả Hàng & Hoàn Tiền</a>
        <a href="#">Chăm Sóc Khách Hàng</a>
      </div>

      <div class="box">
        <h3>Thông Tin Liên Hệ</h3>
        <a href="#">0123 456 789</a>
        <a href="#">Handmade@gmail.com</a>
        <a href="#">116-Ngũ Hành Sơn, Đà Nẵng</a>
        <img src="~/Uploads/tt.jpg" alt="image" />
      </div>
    </div>

    <div class="credit">
      &copy;2024 <span>Handmade</span> | Tất Cả Các Quyền Được Bảo Lưu.
    </div>
  </section>
  <script>
    function addProductToCart(str) {
      fetch(`/Cart/AddProduct/${str}`);
    }
    function addProductToHeart(str) {
      fetch(`/Heart/AddProduct/${str}`);
    }
    function addTutorialToHeart(str) {
      fetch(`/Heart/AddTutorial/${str}`)
    }
  </script>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/script.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>

</html>