Controllers/CartController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Handmade_Dotnet.Models;

namespace Handmade_Dotnet.Controllers;

public class CartController : Controller
{
    public ProductService productService=new ProductService();
    public UserCartService userCartService=new UserCartService();
    public IActionResult Index()
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        List<ProductModel> cartProducts = userCartService.GetByUsername(username); //---------------------------
        ViewBag.cartProducts = cartProducts;
        List<UserCartModel> cart=userCartService.GetAll(username);
        ViewBag.cart = cart;
        List<ProductModel> products = productService.GetAll();
        ViewBag.products = products;
        ViewBag.username=username;
        return View();
    }

    public IActionResult AddProduct(String id)
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        // var product=userCartService.GetByUsername(username);
        var p=userCartService.GetById(id,username);
        if (p != null) {p.Quantity+=1; userCartService.Update(p);}
        else{
        UserCartModel userCartModel= new UserCartModel(username,id,1);
        userCartService.Add(userCartModel);
        }
        return Redirect(Request.Headers.Referer.ToString());
    }

    public IActionResult DeleteProduct(String id)
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        userCartService.Delete(id,username);
        return Redirect(Request.Headers.Referer.ToString());
    }

    public IActionResult UpdateQuantity(int id,string productId)
    {
        Console.WriteLine($"Received quantity: {id}, productId: {productId}");
        userCartService.SetQuantity(id,productId);
        return Redirect(Request.Headers.Referer.ToString());
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/CheckoutController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Handmade_Dotnet.Models;

namespace Handmade_Dotnet.Controllers;

public class CheckoutController : Controller
{
     public ProductService productService=new ProductService();
    public UserCartService userCartService=new UserCartService();

    public IActionResult Index()
    {
        var username = HttpContext.Session.GetString("ten_user");
        if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
        List<ProductModel> cartProducts = userCartService.GetByUsername(username); //---------------------------
        ViewBag.cartProducts = cartProducts;
        List<UserCartModel> userCartModels = userCartService.GetAll(username);
        ViewBag.userCartModels = userCartModels;
         foreach (var item in userCartModels)
        {
            Console.WriteLine($"UserId: {item.Username}, ProductId: {item.ProductId}, Quantity: {item.Quantity}");
        }
        ViewBag.username=username;
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProductController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Handmade_Dotnet.Models;

namespace Handmade_Dotnet.Controllers;

public class ProductController : Controller
{
    public ProductService productService= new ProductService();
    public IActionResult Index()
    {
        List<ProductModel> products = productService.GetAll();
        products.Reverse();
        ViewBag.Products=products;
        var username = HttpContext.Session.GetString("ten_user");
        ViewBag.username=username;
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Cart/Index.cshtml
@{
  ViewData["Title"] = "Cart Page";
  var cart = ViewBag.cart as List<UserCartModel>;
}

<section class="cart">
  <div class="icons">
    <i class="fa-solid fa-cart-plus"></i>
  </div>

  <div class="gh">
    <span>Giỏ hàng của bạn</span>
    <form class="tk" action="" style="display: none">
      <input type="text" placeholder="Tìm kiếm..." name="search" />
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>

  <div class="tu">
    <div class="cb"></div>
    <div class="pr">Sản phẩm</div>
    <div class="na">Tên sản phẩm</div>
    <div class="pri">Đơn giá</div>
    <div class="num">Số lượng</div>
    <div class="mon">Số tiền</div>
    <div class="ope">Thao tác</div>
  </div>
  @{
    int total = 0;
    if (ViewBag.cartProducts != null)
    {
      int i = 0;
      foreach (var product in ViewBag.cartProducts)
      {
        <div class="tu1">
          <div class="cb"><input type="checkbox" /></div>
          <div class="pr"><img src="~/uploads/@product.Image" alt="image" /></div>
          <div class="na">@product.ProductName</div>
          <div class="pri">
            <span>&#8363;@product.OriginalPrice.ToString("#,##0", new
        System.Globalization.CultureInfo("vi-VN")).Replace(",", ".")</span>
            &#8363;@product.DiscountedPrice.ToString("#,##0", new
          System.Globalization.CultureInfo("vi-VN")).Replace(",", ".")
          </div>
          <div class="num">
            <button class="dec">-</button>
            <input class="cen" type="text" value="@cart[i].Quantity" productId="@product.ProductId" />
            <button class="in">+</button>
          </div>
          <div class="mon">&#8363;@((product.DiscountedPrice * cart[i].Quantity).ToString("#,##0", new
      System.Globalization.CultureInfo("vi-VN")).Replace(",", "."))</div>
          <div class="ope">
            <form action="@Href($"/Cart/DeleteProduct/{product.ProductId}")">
              <button type="submit">Xoá</button>
            </form>
            @* <br />
      Tìm sản phẩm tương tự <i class="fa-solid fa-caret-down"></i> *@
          </div>
        </div>
        i++;
        total += product.DiscountedPrice;
      }
    }
  }

  <div class="tu2">
    <div class="cb" style="visibility: hidden;"><input type="checkbox" /></div>
    <div class="se" style="visibility: hidden;">Chọn tất cả</div>
    <div class="del" style="visibility: hidden;">Xoá</div>
    <div class="save" style="visibility: hidden;">Lưu vào mục yêu thích</div>
    <div class="num">Tổng thanh toán: &#8363;@total.ToString("#,##0", new
      System.Globalization.CultureInfo("vi-VN")).Replace(",", ".")
    </div>
    <form asp-area="" asp-controller="Checkout" asp-action="Index">
      <button type="submit">Mua hàng</button>
    </form>
  </div>

  <div class="may">
    <div>CÓ THỂ BẠN CŨNG THÍCH</div>
    <a asp-area="" asp-controller="Product" asp-action="Index">Xem tất cả ></a>
  </div>

  <div class="tu3">
    @{
      int count = 0;
      foreach (var product in ViewBag.products)
      {
        if (count > 4) break;
        <div class="box">
          <span class="discount">-@product.DiscountPercentage%</span>
          <div class="image">
            <img src="~/uploads/@product.Image" alt="image" />
            <div class="iconss">
              <button onclick="addProductToHeart('@product.ProductId')" class="fas fa-heart"></button>
              <form action="@Href($"/Cart/AddProduct/{product.ProductId}")">
                <button class="cart-btn" type="submit">Thêm vào giỏ</button>
              </form>
              <button href="#" class="fas fa-share"></button>
            </div>
          </div>
          <div class="content">
            <h3>@product.ProductName</h3>
            <div class="price">
              &#8363;@product.DiscountedPrice.ToString("#,##0", new
          System.Globalization.CultureInfo("vi-VN")).Replace(",",
          ".")<span>&#8363;@product.OriginalPrice.ToString("#,##0", new
            System.Globalization.CultureInfo("vi-VN")).Replace(",", ".")</span>
            </div>
          </div>
        </div>
        count++;
      }
    }
  </div>
</section>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('.tu1').forEach(function (productElement) {
      var decButton = productElement.querySelector('.dec');
      var inButton = productElement.querySelector('.in');
      var quantityInput = productElement.querySelector('.cen');

      decButton.addEventListener('click', function () {
        var currentValue = parseInt(quantityInput.value, 10);
        if (currentValue > 1) {
          currentValue--;
          quantityInput.value = currentValue;
          updateTotalPrice(productElement);
        }
      });

      inButton.addEventListener('click', function () {
        var currentValue = parseInt(quantityInput.value, 10);
        currentValue++;
        quantityInput.value = currentValue;
        updateTotalPrice(productElement);
      });
    });
  });

  function updateTotalPrice(productElement) {
    var quantity = parseInt(productElement.querySelector('.cen').value, 10);
    var quantityInput = productElement.querySelector('.cen');
    var productId = quantityInput.getAttribute('productId');

    // Cập nhật số lượng sản phẩm thông qua fetch
    fetch(`/Cart/UpdateQuantity/${quantity}?productId=${productId}`)
      .then(response => {
        if (!response.ok) {
          throw new Error('Cập nhật số lượng thất bại');
        }
        return response.json();
      })
      .catch(error => console.error('Error:', error));

    // Lấy giá sau khi giảm
    var discountedPriceText = productElement.querySelector('.pri').childNodes[2].textContent.trim();
    var discountedPrice = parseFloat(discountedPriceText.replace(/[^0-9.-]+/g, ""));

    // Kiểm tra giá trị hợp lệ và tính tổng số tiền
    if (!isNaN(discountedPrice) && !isNaN(quantity)) {
      var totalPrice = discountedPrice * quantity;
      productElement.querySelector('.mon').innerHTML = `&#8363;${totalPrice.toLocaleString('de-DE', {
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
      }).replace(',', '.')}`;
    } else {
      console.error('Invalid price or quantity');
    }
  }
</script>